"""empty message

Revision ID: 5aa03709332c
Revises: 8dc2b75daa43
Create Date: 2022-06-15 09:02:14.089673

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5aa03709332c'
down_revision = '8dc2b75daa43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('text', sa.String(length=120), nullable=False))
    op.drop_index('label', table_name='task')
    op.drop_index('label_2', table_name='task')
    op.drop_column('task', 'label')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('label', mysql.VARCHAR(length=120), nullable=False))
    op.create_index('label_2', 'task', ['label'], unique=False)
    op.create_index('label', 'task', ['label'], unique=False)
    op.drop_column('task', 'text')
    # ### end Alembic commands ###
